### ISSUE TITLE
Add a logo?

### ISSUE THREAD

**Issue by abysssol** [blainehansen/magmide#30]
I admit that it's not especially important, but the lack of a logo was rather noticeable (to me, at least).

I threw together a logo that you can use if you want (I hereby release it under the [Creative Commons Zero](https://creativecommons.org/publicdomain/zero/1.0/)). I'm no graphic designer, so it's just a "programmer art" level placeholder, but it seems to me that a temporary logo is better than no logo (or GitHub's auto-generated logo, as is the actual case).

If you are interested in adding a logo, but don't like my current iteration, I can also make modifications or an entirely new design based on your suggestions and feedback.

Fascinating project, by the way; I truly hope it succeeds. I am interested in helping, though the suggested reading on formal verification was a little intimidating, and I still haven't gotten around to it. If there's anything else I can do (or that you think I might be able to do), it won't hurt to ask (my email is <abysssol@pm.me>). I do know rust pretty well, so perhaps I might be able to help with algorithm implementation, allowing you to focus more on design.

<div align="center">

[download png](https://github.com/user-attachments/assets/838950f1-78cb-4efd-8687-bec06fe86fbf)
[download svg](https://github.com/user-attachments/assets/58681a1a-c83c-41d9-afae-ab6e62eb8b5f)

<img width="128" height="128" src="https://github.com/user-attachments/assets/838950f1-78cb-4efd-8687-bec06fe86fbf">

</div>

**Comment by blainehansen** [comment]
I appreciate your desire to help :) Honestly the reason I haven't done anything more "marketing"-like is on purpose. The project isn't far enough technically for me to feel like it's responsible to really promote it or pretend there's much to pay attention to, and I don't want to give people the wrong idea or distract myself with things that aren't the core problem. I want to avoid being a "diamond dust" project ha:
https://oxide.computer/podcasts/on-the-metal/jonathan-blow (go to transcript, ctrl+f for "diamond dust")

Thank you though! I'm glad the idea of the project is inspiring :) When I've figured out how to proceed you'll see things start to happen!
